on: [push]
name: build
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1.1
        with:
          ghc-version: "8.8.3"
          cabal-version: "latest"
          enable-stack: true
          stack-version: "latest"
      - run: stack install alex happy
      - run: stack install
      - run: make test-coverage
      - run: make coverage-lcov
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
