on: [push]
name: build
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1.1.3
        with:
          ghc-version: "8.8.3"
          cabal-version: "latest"
          enable-stack: true
          stack-version: "latest"
      - run: sudo apt-get update -y
      - run: sudo apt-get install -y lcov
      - run: stack install alex happy
      - run: stack install
      - run: ./scripts/test coverage
      - run: ./scripts/coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
